Fix flash error processing
Regeexp is changed to a greedy one to handle lines like

        error: ENOENT: not such file or directory

Change-type: patch
Signed-off-by: Roman Mazur <roman@balena.io>